PANAGroupJobWebApp/Controllers/ArithController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PANAGroupJobWebApp.Models;

namespace PANAGroupJobWebApp.Controllers
{
    public class ArithController : Controller
    {
        //
        // GET: /Arith/
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult Index(int? m, int? n)
        {
            var model = new ArithModel
            {
                Sum = m + n,
                Difference = m - n,
                Multiplication = m * n,
                Ratio = n == 0 ? "?" : (m / n).ToString(),
                Remain = n == 0 ? "?" : (m % n).ToString(),
                M = m,
                N = n
            };

            return View(model);
        }

    }
}

PANAGroupJobWebApp/Views/Arith/Index.cshtml
@model PANAGroupJobWebApp.Models.ArithModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Arith</h2>

@using (Html.BeginForm("Index", "Arith"))
{
    <fieldset>
        <legend>Do some math</legend>
        <div>
            @Html.DisplayNameFor(m => m.M)
            @Html.TextBoxFor(m => m.M)
        </div>
        <div>
            @Html.DisplayNameFor(m => m.N)
            @Html.TextBoxFor(m => m.N)
        </div>
        <div>
            @Html.DisplayNameFor(m => m.Sum)
            @Html.DisplayFor(m => m.Sum)
        </div>
        <div>
            @Html.DisplayNameFor(m => m.Difference)
            @Html.DisplayFor(m => m.Difference)
        </div>
        <div>
            @Html.DisplayNameFor(m => m.Multiplication)
            @Html.DisplayFor(m => m.Multiplication)
        </div>
        <div>
            @Html.DisplayNameFor(m => m.Ratio)
            @Html.DisplayFor(m => m.Ratio)
        </div>
        <div>
            @Html.DisplayNameFor(m => m.Remain)
            @Html.DisplayFor(m => m.Remain)
        </div>

        <input type="submit" value="Eval" />
    </fieldset>
}

