PANAGroupJobWebApp/Controllers/ObjController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using PANAGroupJobWebApp.DataLayer;
using PANAGroupJobWebApp.Models.ViewModels;

namespace PANAGroupJobWebApp.Controllers
{
    public class ObjController : Controller
    {
        //
        // GET: /HtmlObj/
        private NorthwindEntities context = new NorthwindEntities();

        public ActionResult Html()
        {
            var data = context.Products.Select(p =>
                new HtmlViewModel
                {
                    ProductId = p.ProductID,
                    ProductName = p.ProductName,
                    CategoryName = p.Categories.CategoryName,
                    CompanyName = p.Suppliers.CompanyName,
                    Country = p.Suppliers.Country
                });

            return View(data);
        }

        // GET: /WebGrid/
        public ActionResult WebGrid(int page = 1, int rowsPerPage = 10, string sort = "ProductID", string sortDir = "ASC")
        {
            var data = GetProducts(page, rowsPerPage, sort, sortDir);
            return View(data);
        }



        // Data for WebGridObj
        private WebGridViewModel GetProducts(int page, int rowsPerPage, string sort, string sortDir)
        {
            var query = context.Products.Select(p => new 
            {
                p.ProductID,
                p.ProductName,
                p.Categories.CategoryName,
                p.Suppliers.CompanyName,
                p.Suppliers.Country
            }).OrderBy(sort + " " + sortDir);

            WebGridViewModel model = new WebGridViewModel
            {
                TotalRows = query.Count(),
                Products = query.Skip((page - 1) * rowsPerPage).Take(rowsPerPage).ToList().Select(p =>
                   new HtmlViewModel
                   {
                       ProductId = p.ProductID,
                       ProductName = p.ProductName,
                       CategoryName = p.CategoryName,
                       CompanyName = p.CompanyName,
                       Country = p.Country
                   })
            };
            return model;
        }

    }
}

PANAGroupJobWebApp/Controllers/SqlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PANAGroupJobWebApp.Models.ViewModels;
using System.Linq.Dynamic;


namespace PANAGroupJobWebApp.Controllers
{
    public class SqlController : Controller
    {
        //
        // GET: /Sql/

        public ActionResult WebGrid(int page = 1, int rowsPerPage = 10, string sort = "ProductID", string sortDir = "ASC")
        {
            var model = GetProducts(page, rowsPerPage, sort, sortDir);

            return View(model);
        }

        private WebGridViewModel GetProducts(int page, int rowsPerPage, string sort, string sortDir)
        {
            using (Northwind context = new Northwind(@"Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\northwnd.mdf;Integrated Security=True;Connect Timeout=30"))
            {
                var query = context.Products.Select(p => new
                {
                    p.ProductID,
                    p.ProductName,
                    p.Category.CategoryName,
                    p.Supplier.CompanyName,
                    p.Supplier.Country
                }).OrderBy(sort + " " + sortDir);

                WebGridViewModel model = new WebGridViewModel
                {
                    TotalRows = query.Count(),
                    Products = query.Skip((page - 1) * rowsPerPage).Take(rowsPerPage).ToList().Select(p =>
                       new HtmlViewModel
                       {
                           ProductId = p.ProductID,
                           ProductName = p.ProductName,
                           CategoryName = p.CategoryName,
                           CompanyName = p.CompanyName,
                           Country = p.Country
                       })
                };
                return model;
            }
        }

    }
}

PANAGroupJobWebApp/Controllers/XmlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PANAGroupJobWebApp.Models.ViewModels;
using System.Linq.Dynamic;
using System.Xml.Linq;

namespace PANAGroupJobWebApp.Controllers
{
    public class XmlController : Controller
    {
        //
        // GET: /Xml/

        public ActionResult WebGrid(int page = 1, int rowsPerPage = 10, string sort = "ProductID", string sortDir = "ASC")
        {
            var model = GetProducts(page, rowsPerPage, sort, sortDir);
            return View(model);
        }

        private WebGridViewModel GetProducts(int page, int rowsPerPage, string sort, string sortDir)
        {
            string path = System.Web.HttpContext.Current.Server.MapPath(@"~\App_Data");
            var Products = XElement.Load(path + @"\XProducts.xml");
            var Categories = XElement.Load(path + @"\XCategories.xml");
            var Suppliers = XElement.Load(path + @"\XSuppliers.xml");

            var query = Products.Descendants("Product")
                .Join(Categories.Descendants("Category"), product => product.Element("CategoryID").Value, category => category.Element("CategoryID").Value,
                    (product, category) =>
                        new
                        {
                            ProductID = product.Element("ProductID").Value,
                            ProductName = product.Element("ProductName").Value,
                            CategoryName = category.Element("CategoryName").Value,
                            SupplierID = product.Element("SupplierID").Value
                        })
                .Join(Suppliers.Descendants("Supplier"), product => product.SupplierID, supplier => supplier.Element("SupplierID").Value,
                    (product, supplier) =>
                        new HtmlViewModel
                        {
                            ProductId = Int32.Parse(product.ProductID),
                            ProductName = product.ProductName,
                            CategoryName = product.CategoryName,
                            CompanyName = supplier.Element("CompanyName").Value,
                            Country = supplier.Element("Country").Value
                        })
                .AsQueryable<HtmlViewModel>().OrderBy(sort + " " + sortDir);

            WebGridViewModel model = new WebGridViewModel
            {
                TotalRows = query.Count(),
                Products = query.Skip((page - 1) * rowsPerPage).Take(rowsPerPage).ToList()
            };
            return model;
        }

    }
}

PANAGroupJobWebApp/Views/Shared/_GridPartial.cshtml
<div>
    @{
        var grid = new WebGrid(null, defaultSort: "ProductId");
        grid.Bind(Model.Products, rowCount: Model.TotalRows, autoSortAndPage: false);
        if (!string.IsNullOrWhiteSpace(grid.SortColumn))
        {
        <script type="text/javascript">
            if ($(document).ready(function () {
                $('thead > tr > th > a[href*="sort=@grid.SortColumn"]').parent().addClass('@(grid.SortDirection == SortDirection.Ascending ? "asc" : "desc")');
            }));
        </script>
        }

    }
    @grid.GetHtml(columns: grid.Columns(
        grid.Column("ProductId"),
        grid.Column("ProductName"),
        grid.Column("CategoryName"),
        grid.Column("CompanyName"),
        grid.Column("Country")
            ))

</div>


PANAGroupJobWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Arith", "Index", "Arith")</li>
                            <li>@Html.ActionLink("HtmlObj", "Html", "Obj")</li>
                            <li>@Html.ActionLink("WebGridObj", "WebGrid", "Obj")</li>
                            <li>@Html.ActionLink("WebGridSql", "WebGrid", "Sql")</li>
                            <li>@Html.ActionLink("WebGridXml", "WebGrid", "Xml")</li>
                            <li>@Html.ActionLink("WebGridOdata", "WebGrid", "OData")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        
        @RenderSection("scripts", required: false)
    </body>
</html>